spring:
    kafka:
        bootstrap-servers: kafka:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# logging:
#     level:
#         '[org.apache.kafka]': DEBUG
#         '[org.springframework.kafka.support.serializer]': DEBUG

# logging:
#   level:
#     '[org.springframework.kafka.listener]': DEBUG
#     '[org.apache.kafka.clients.consumer]': DEBUG

